### ISSUE TITLE
How many files for the balanced dataset?

### ISSUE THREAD

**Issue by sailorbj** [jim-schwoebel/download_audioset#5]
When complete downloading, how many wavs are there for the balanced dataset?

**Comment by CHeggan** [comment]
For the balanced training and evaluation sets, there are 22,176 and 20,383 files in the meta-data provided by Google respectively.  Details here: https://research.google.com/audioset/download.html

The actual amount downloaded will vary from instance to instance due to the exceptions covered in the main repository, e.g private videos or removals, etc. These will fluctuate frequently and so exact numbers at any given time are hard to get.

These reported numbers should at least be fairly close to the actual amount avaiable at the end of downloading.
